;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Ошибка
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[FRAME_CONFIRMATION_POPUP]
command = click
command = deactivate,event:HideConfirmationPopup
command = activate,event:HideConfirmationPopup
captionheight = 54
captiondividerheight = 16
backimage		= piclist=PAPER_BIG, picname=paper, color=(255,128,128,128)

[FRAME_GOLD_CONFIRMATION_POPUP]

[TITLE_BACKGROUND_POPUP]
position = 605,50,1315,86

[FADER_CONFIRMATION_POPUP]
position = -1,-1,1920,1080
leftColor = 150,0,0,0
topColor = 150,0,0,0
rightColor = 150,0,0,0
bottomColor = 150,0,0,0
borderColor = 0,0,0,0

[HEADER_CONFIRMATION_POPUP]
class 			= formatedtext
position		= 8,14,592,47
alignment		= center
fontscale		= 2.0
lineSpace		= 25
Color			= 255,255,255,255
font			= interface_normal

[TEXT_CONFIRMATION_POPUP]
position = 730,456,1190,590
fontScale = 1.7
lineSpace = 30
alignment = center

[OK_BUTTON_CONFIRMATION_POPUP]
bBreakCommand = 1
command = click,event:ButtonConfirmationOK
command = deactivate,event:HideConfirmationPopup
command = activate,event:ButtonConfirmationOK
position = 690,590,945,650
string = Yes
command = leftstep,select:OK_BUTTON_CONFIRMATION_POPUP
command = rightstep,select:CANCEL_BUTTON_CONFIRMATION_POPUP

[CANCEL_BUTTON_CONFIRMATION_POPUP]
bBreakCommand = 1
command = click,event:HideConfirmationPopup
command = deactivate,event:HideConfirmationPopup
command = activate,event:HideConfirmationPopup
position = 975,590,1230,650
string = Cancel
command = leftstep,select:OK_BUTTON_CONFIRMATION_POPUP
command = rightstep,select:CANCEL_BUTTON_CONFIRMATION_POPUP
