void ApplyMigration(ref migrationState)
{
    EncWeightBase[ENCOUNTER_TYPE_MERCHANT_SMALL] = 27;
    EncWeightBase[ENCOUNTER_TYPE_MERCHANT_MEDIUM] = 17;
    EncWeightBase[ENCOUNTER_TYPE_MERCHANT_LARGE] = 11;
    EncWeightBase[ENCOUNTER_TYPE_MERCHANT_CROWN] = 5;
    EncWeightBase[ENCOUNTER_TYPE_MERCHANT_EXPEDITION] = 4;
    EncWeightBase[ENCOUNTER_TYPE_MERCHANT_SLAVES] = 6;
    EncWeightBase[ENCOUNTER_TYPE_PATROL_SMALL] = 9;
    EncWeightBase[ENCOUNTER_TYPE_PATROL_MEDIUM] = 8;
    EncWeightBase[ENCOUNTER_TYPE_NAVAL_MEDIUM] = 4;
    EncWeightBase[ENCOUNTER_TYPE_NAVAL_LARGE] = 3;
    EncWeightBase[ENCOUNTER_TYPE_SMUGGLERS] = 0;
    EncWeightBase[ENCOUNTER_TYPE_PIRATE] = 8;
}
