[IMAGE]
RelativePosX = 0.875
RelativePosY = 0.78
RelativeWidth = 0.13
RelativeHeight = 0.13
HorisontalFramesCount = 8
VerticalFramesCount = 8

[TIPS]
font = interface_normal
lineSpace = 50
;     = 0xFFFFFFFF
color = 4294967295
scale = 2.5
RelativePosX = 0.5
RelativePosY = 0.8
RelativeWidth = 0.5
