;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Sith Интерфейс "Главное меню"
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[MAIN]
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;	MAIN_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = RECTANGLE,FLAG_FIX
item = VIDEO,FLAG
item = LOGO,LOGO
item = L_EYES,EYES
item = FORMATEDTEXT,VERSION_TEXT
item = FORMATEDTEXT,COPYRIGHT_TEXT
item = FORMATEDTEXT,NEW_GAME_INFO
item = TEXTBUTTON,RESUME_GAME
item = TEXTBUTTON,NEW_GAME
item = TEXTBUTTON,LOAD_GAME
item = TEXTBUTTON,OPTIONS
item = TEXTBUTTON,CREDITS
item = TEXTBUTTON,QUIT
item = ALERT,A_UPDATES
item = TEXTBUTTON,UPDATES
item = TEXTBUTTON,NEWS
item = TEXTBUTTON,WORKSHOP
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;	REWARDS
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 1000,TRIGGER,TRIGGER
item = FRAME,REWARDS_BACKGROUND
item = FORMATEDTEXT,REWARDS_TITLE
item = PICTURE,REWARD_ITEM_1
item = PICTURE,REWARD_ITEM_2
item = PICTURE,REWARD_ITEM_3
item = PICTURE,REWARD_ITEM_4
item = PICTURE,REWARD_ITEM_5
item = PICTURE,REWARD_AVAILABLE_1
item = PICTURE,REWARD_AVAILABLE_2
item = PICTURE,REWARD_AVAILABLE_3
item = PICTURE,REWARD_AVAILABLE_4
item = PICTURE,REWARD_AVAILABLE_5
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; REWARD_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 100,FRAME_DESCRIPTOR,DESCRIPTOR_1
item = 100,FRAME_DESCRIPTOR,DESCRIPTOR_2
item = 100,FRAME_DESCRIPTOR,DESCRIPTOR_3
item = 100,FRAME_DESCRIPTOR,DESCRIPTOR_4
item = 100,FORMATEDTEXT,DESCRIPTOR_1_VALUE
item = 100,FORMATEDTEXT,DESCRIPTOR_2_VALUE
item = 100,FORMATEDTEXT,DESCRIPTOR_3_VALUE
item = 100,FORMATEDTEXT,DESCRIPTOR_4_VALUE
item = 100,FORMATEDTEXT,REWARD_NAME
item = 100,PICTURE,REWARD_PICTURE
item = 100,FORMATEDTEXT,REWARD_CONDITIONS
item = 100,FORMATEDTEXT,ITEM_TYPE
item = 101,FORMATEDTEXT,ITEM_WEIGHT_VALUE
item = 100,FRAME,ITEM_WEIGHT_BACKGROUND
item = 100,FORMATEDTEXT,REWARD_DESCRIPTION
item = FRAME2,FRAME_INFO
item = TABLE,TABLE_ITEM_STATS
item = 100,TEXTBUTTON4,GET_REWARD_BUTTON
item = 100,TEXTBUTTON4,REWARD_CLOSE_BUTTON
item = WINDOW,REWARD_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;	CONFIRM_EXIT_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 80,FADER,CONFIRM_EXIT_FADER
item = 81,MSG_FRAME,CONFIRM_EXIT_FRAME
item = 82,FRAME_GOLD_MSG,CONFIRM_EXIT_FRAMEGOLD
item = 82,FORMATEDTEXT,CONFIRM_EXIT_TEXT
item = 82,TEXTBUTTON,CONFIRM_EXIT_YES
item = 82,TEXTBUTTON,CONFIRM_EXIT_NO
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;	NEWS_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 80,FADER,NEWS_FADER
item = 81,FRAME,NEWS_FRAME
item = 82,PAPERW,NEWS_PAPER
item = 82,TOOLTIP_TITLERECT,NEWS_TITLERECT
item = 82,FORMATEDTEXT,NEWS_TITLE
item = 82,FORMATEDTEXT,NEWS_TEXT
item = 82,SCROLLER,NEWS_SCROLL_TEXT
item = 82,TEXTBUTTON,B_BACK
item = 82,TEXTBUTTON,B_MORE
item = 83,FRAME_GOLD,NEWS_FRAMEGOLD
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;	ATTENTION_WINDOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = 80,FADER,ATTENTION_FADER
item = 81,MSG_FRAME,ATTENTION_FRAME
item = 82,FRAME_GOLD_MSG,ATTENTION_FRAMEGOLD
item = 82,FORMATEDTEXT,ATTENTION_TEXT
item = 82,TEXTBUTTON,ATTENTION_OK
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
item = WINDOW,MAIN_WINDOW
item = WINDOW,CONFIRM_EXIT_WINDOW
item = WINDOW,NEWS_WINDOW
item = WINDOW,ATTENTION_WINDOW

[MAIN_WINDOW]
show = 1
nodelist = LOGO,VERSION,RESUME_GAME,NEW_GAME,LOAD_GAME,OPTIONS,CREDITS,QUIT,A_UPDATES,UPDATES,NEWS,WORKSHOP
nodelist = REWARDS_TITLE,REWARDS_BACKGROUND,REWARD_ITEM_1,REWARD_ITEM_2,REWARD_ITEM_3,REWARD_ITEM_4,REWARD_ITEM_5,REWARD_AVAILABLE_1,REWARD_AVAILABLE_2,REWARD_AVAILABLE_3,REWARD_AVAILABLE_4,REWARD_AVAILABLE_5

[FLAG_FIX]
position = 85,-250,465,0
leftColor = 255,60,60,60
topColor = 255,60,60,60
rightColor = 255,60,60,60
bottomColor = 255,60,60,60
borderColor = 0,0,0,0
[FLAG]
position = 60,-1,480,1080
sTexture = blackflag
color = 255,225,225,225

[VERSION_TEXT]
bAbsoluteRectangle = 5
position = 1400,10,1910,30
fontScale = 1.5
lineSpace = 20
alignment = right
font = interface_normal_credits

[COPYRIGHT_TEXT]
bAbsoluteRectangle = 5
position = 1400,40,1910,60
fontScale = 1.5
lineSpace = 20
alignment = right
font = interface_normal_credits

[NEW_GAME_INFO]
position = 130,358,420,418
font = interface_button
fontScale = 1.0
lineSpace = 28
alignment = center
color = 155,255,128,128
string = New Game Restart

[RESUME_GAME]
command = click
command = activate
command = downstep,select:NEW_GAME
position = 90,300,460,360
string = Resume Game
command = deactivate

[NEW_GAME]
command = click
command = activate
command = upstep,select:RESUME_GAME
command = downstep,select:LOAD_GAME
position = 90,360,460,420
string = New Game
command = deactivate

[LOAD_GAME]
command = click
command = activate
command = upstep,select:NEW_GAME
command = downstep,select:OPTIONS
position = 90,420,460,480
string = Load
command = deactivate

[OPTIONS]
command = click
command = activate
command = upstep,select:LOAD_GAME
command = downstep,select:CREDITS
position = 90,480,460,540
string = Options
command = deactivate

[CREDITS]
command = click
command = activate
command = upstep,select:OPTIONS
command = downstep,select:QUIT
position = 90,540,460,600
string = Credits
command = deactivate

[QUIT]
command = click
command = activate
command = downstep
command = upstep,select:CREDITS
position = 90,600,460,660
string = Quit
command = deactivate

[A_UPDATES]
position = 414,737,440,763

[UPDATES]
command = click
command = activate
command = upstep,select:QUIT
command = downstep,select:NEWS
position = 90,720,460,780
string = Updates
command = deactivate

[NEWS]
command = click
command = activate
command = upstep
command = downstep,select:WORKSHOP
position = 90,780,460,840
string = News
command = deactivate

[WORKSHOP]
command = click
command = activate
command = upstep,select:NEWS
position = 90,840,460,900
string = Steam Workshop
command = deactivate

[CONFIRM_EXIT_WINDOW]
show = 0
nodelist = CONFIRM_EXIT_FADER,CONFIRM_EXIT_FRAME,CONFIRM_EXIT_FRAMEGOLD
nodelist = CONFIRM_EXIT_TEXT,CONFIRM_EXIT_YES,CONFIRM_EXIT_NO

[CONFIRM_EXIT_TEXT]
position = 680,490,1240,530
string = Confirm_exit_from_menu
fontScale = 1.75

[CONFIRM_EXIT_YES]
command = deactivate,event:ConfirmExitCancel
command = click,event:ConfirmExitClick
command = activate,event:ConfirmExitClick
command = rightstep,select:CONFIRM_EXIT_NO
position = 690,590,945,650
string = Yes

[CONFIRM_EXIT_NO]
command = deactivate,event:ConfirmExitCancel
command = click,event:ConfirmExitCancel
command = activate,event:ConfirmExitCancel
command = leftstep,select:CONFIRM_EXIT_YES
position = 975,590,1230,650
string = No

[NEWS_WINDOW]
show = 0
nodelist = NEWS_FADER,NEWS_FRAME,NEWS_PAPER,NEWS_TITLERECT,NEWS_FRAMEGOLD
nodelist = NEWS_TITLE,NEWS_TEXT,NEWS_SCROLL_TEXT,EXIT_BTN,EXIT_BTNE
nodelist = B_BACK,B_MORE

[NEWS_FRAME]
position = 620,240,1300,840
captionheight = 47
captiondividerheight = 12

[NEWS_FRAMEGOLD]
position = 630,250,1290,825
lefttop_size = 40,50
righttop_size = 40,50
leftbottom_size = 40,50
rightbottom_size = 40,50

[NEWS_PAPER]
position = 630,295,1290,755

[NEWS_TITLERECT]
position = 630,250,1290,290

[NEWS_TITLE]
position = 630,252,1290,287
string = News
fontScale = 2.0

[NEWS_TEXT]
position = 650,305,1268,745
alignment = left
fontscale = 1.6
lineSpace = 25
color = 255,47,39,29;
font = interface_stextw
scrollerName = NEWS_SCROLL_TEXT
command = downstep
command = upstep
command = speeddown
command = speedup
command = deactivate,event:NewsCancel
command = activate,select:NEWS_TEXT
command = click,select:NEWS_TEXT
command = leftstep,select:B_BACK
command = rightstep,select:B_MORE

[NEWS_SCROLL_TEXT]
command = click,select:NEWS_TEXT
command = deactivate,event:NewsCancel
command = downstep
command = upstep
position = 1260,310,1285,740
ownedcontrol = NEWS_TEXT
rollerHeight = 120
[B_BACK]
command = activate,event:NewsCancel
command = deactivate,event:NewsCancel
command = click,event:NewsCancel
command = rightstep,select:B_MORE
command = downstep,select:NEWS_TEXT
command = upstep,select:NEWS_TEXT
command = speeddown,select:NEWS_TEXT
command = speedup,select:NEWS_TEXT
position = 650,760,850,810
string = Close
strOffset = 8
[B_MORE]
command = activate
command = click
command = deactivate,event:NewsCancel
command = leftstep,select:B_BACK
command = downstep,select:NEWS_TEXT
command = upstep,select:NEWS_TEXT
command = speeddown,select:NEWS_TEXT
command = speedup,select:NEWS_TEXT
position = 1000,760,1270,810
string = NewsMore
strOffset = 8
[ATTENTION_WINDOW]
show = 0
nodelist = ATTENTION_FADER,ATTENTION_FRAME,ATTENTION_FRAMEGOLD
nodelist = ATTENTION_TEXT,ATTENTION_OK

[ATTENTION_TEXT]
position = 670,436,1250,576
fontScale = 1.75
[ATTENTION_OK]
command = deactivate,event:AttentionCancel
command = click,event:AttentionCancel
command = activate,event:AttentionCancel
position = 835,590,1085,650
string = Ok

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Интеграция с франшизой
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[REWARDS_BACKGROUND]
backimage = piclist=INFO_FADER_C, picname=paper, color=(245,128,128,128)
position = 1404,881,1920,1010

[REWARDS_TITLE]
position = 1478,886,1846,934
font = interface_button
fontScale = 1.4
lineSpace = 28
alignment = center
string = Award

[REWARD_ITEM_1]
position = 1466,939,1530,1003
command = click,event:MM_ShowReward
[REWARD_ITEM_2]
position = 1548,939,1612,1003
command = click,event:MM_ShowReward
[REWARD_ITEM_3]
position = 1630,939,1694,1003
command = click,event:MM_ShowReward
[REWARD_ITEM_4]
position = 1712,939,1776,1003
command = click,event:MM_ShowReward
[REWARD_ITEM_5]
position = 1794,939,1858,1003
command = click,event:MM_ShowReward

[REWARD_AVAILABLE_1]
position = 1410,921,1498,1005
textureName = interfaces\usedflag.tga
[REWARD_AVAILABLE_2]
position = 1492,921,1580,1005
textureName = interfaces\usedflag.tga
[REWARD_AVAILABLE_3]
position = 1574,921,1662,1005
textureName = interfaces\usedflag.tga
[REWARD_AVAILABLE_4]
position = 1717,944,1771,998
groupName = HELP_ICONS
picName = HelpLight
color = 175,128,128,128
[REWARD_AVAILABLE_5]
position = 1799,944,1853,998
groupName = HELP_ICONS
picName = HelpLight
color = 175,128,128,128

[REWARD_WINDOW]
show = 0
nodelist = FRAME_INFO,GET_REWARD_BUTTON,REWARD_CLOSE_BUTTON,REWARD_CONDITIONS
nodelist = DESCRIPTOR_1,DESCRIPTOR_2,DESCRIPTOR_3,DESCRIPTOR_4
nodelist = DESCRIPTOR_1_VALUE,DESCRIPTOR_2_VALUE,DESCRIPTOR_3_VALUE,DESCRIPTOR_4_VALUE
nodelist = REWARD_NAME,REWARD_PICTURE,ITEM_TYPE,REWARD_DESCRIPTION
nodelist = ITEM_WEIGHT_BACKGROUND, TABLE_ITEM_STATS, ITEM_WEIGHT_VALUE

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Окно с наградой
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[FRAME_INFO]
position = 692,142,1142,900
backimage = piclist=PAPER_FRAME, picname=paper, color=(255,205,205,205)
captionheight = 44
captiondividerheight = 8
[REWARD_NAME]
position = 736,156,1096,216
fontScale = 1.6
lineSpace = 24
alignment = center
[ITEM_TYPE]
position = 509,352,673,413
fontScale = 1.3
lineSpace = 16
alignment = center
[REWARD_PICTURE]
position = 728,219,888,379
[REWARD_DESCRIPTION]
position = 728,410,1129,610
fontScale = 1.4
lineSpace = 24
alignment = left
command = deactivate
[DESCRIPTOR_1]
position = 932,219,1100,253
UseTrigger = 1
lefttop_size		= 14,14
righttop_size		= 14,14
leftbottom_size		= 14,14
rightbottom_size	= 14,14

[DESCRIPTOR_2]
position = 932,258,1100,292
color			= 185,128,208,238
lefttop_size		= 14,14
righttop_size		= 14,14
leftbottom_size		= 14,14
rightbottom_size	= 14,14
UseTrigger = 1
[DESCRIPTOR_3]
position = 932,297,1100,331
color			= 185,228,148,128
lefttop_size		= 14,14
righttop_size		= 14,14
leftbottom_size		= 14,14
rightbottom_size	= 14,14
UseTrigger = 1
[DESCRIPTOR_4]
position = 932,336,1100,370
UseTrigger = 1
lefttop_size		= 14,14
righttop_size		= 14,14
leftbottom_size		= 14,14
rightbottom_size	= 14,14
color			= 255,156,61,197
[DESCRIPTOR_1_VALUE]
position = 932,226,1100,260
fontScale = 1.2
lineSpace = 20
backOffset = 0,3,0,33
valignment = 1
[DESCRIPTOR_2_VALUE]
position = 932,265,1100,299
fontScale = 1.2
lineSpace = 20
valignment = 1
[DESCRIPTOR_3_VALUE]
position = 932,304,1100,338
fontScale = 1.2
lineSpace = 20
valignment = 1
[DESCRIPTOR_4_VALUE]
position = 932,343,1100,377
fontScale = 1.2
lineSpace = 20
valignment = 1
[TABLE_ITEM_STATS]
position = 717,630,1117,691
selectimage = color=(0,128,128,128)
vlinewidth = 0
hlineheight = 0
borderwidth = 0
iscolselect = 1
vlinewidth = 1
hlineheight = 1
borderwidth = 1
headerlineheight = 0
rowquantity = 1
colquantity = 5
fontcellscale = 1.2
fontcellvalignment = center
colswidth = 100,100,100,100
rowsheight = 62
NormalLineHeight = 45
UseTrigger = 1
UseColTrigger = 1
[REWARD_CONDITIONS]
position = 728,720,1100,816
fontScale = 1.6
lineSpace = 24
alignment = center
[GET_REWARD_BUTTON]
command = click
command = activate
command = deactivate
position = 728,822,909,870
strOffset = 8

[REWARD_CLOSE_BUTTON]
command = activate,event:MM_ShowReward
command = deactivate
command = click,event:MM_ShowReward
command = rightstep,select:B_MORE
command = downstep,select:NEWS_TEXT
command = upstep,select:NEWS_TEXT
command = speeddown,select:NEWS_TEXT
command = speedup,select:NEWS_TEXT
position = 916,822,1100,870
string = Close
strOffset = 8
[ITEM_WEIGHT_VALUE]
position = 760,365,856,403
fontScale = 1.5
lineSpace = 12
alignment = center
[ITEM_WEIGHT_BACKGROUND]
position = 761,330,857,426
backimage = piclist=WEIGHT_FRAME, picname=frame, color=(255,205,205,205)
UseTrigger = 1
TriggerFramePos = 766,362,852,396
