#define SIMPLE_RUMOUR_NUM	95
#define CITIZEN_RUMOUR_NUM	10

string DEFAULT_TEXT[19] = {
"Azt mondják, hogy az Aranyflotta évente kétszer hajózik Porto Belóból. Több tucat kereskedô, akiket hadihajók védenek.  Mindig ugyanazon az útvonalon: Porto Belóból Havannába, majd ha elérte Kubát, északra hajózik az Óvilágba. Nyilvánvaló, hogy a flotta rakterei mérhetetlen kincsekkel vannak tele.",
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
"Azt mondják, hogy Európa megint fel fog robbanni. Újabb háború közeleg, és mint mindig, most is a köznép fog fizetni érte. Remélem, hogy nem fog ideérni, van elég saját problémánk.",
"Azt mondják, hogy az Aranyflotta évente kétszer hajózik Porto Belóból. Több tucat kereskedô, akiket hadihajók védenek.  Mindig ugyanazon az útvonalon: Porto Belóból Havannába, majd ha elérte Kubát, északra hajózik az Óvilágba. Nyilvánvaló, hogy a flotta rakterei mérhetetlen kincsekkel vannak tele.",
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
"Azt mondják, hogy Európa megint fel fog robbanni. Újabb háború közeleg, és mint mindig, most is a köznép fog fizetni érte. Remélem, hogy nem fog ideérni, van elég saját problémánk.",
"Azt mondják, hogy az Aranyflotta évente kétszer hajózik Porto Belóból. Több tucat kereskedô, akiket hadihajók védenek.  Mindig ugyanazon az útvonalon: Porto Belóból Havannába, majd ha elérte Kubát, északra hajózik az Óvilágba. Nyilvánvaló, hogy a flotta rakterei mérhetetlen kincsekkel vannak tele.",
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Azt mondják, hogy az Aranyflotta évente kétszer hajózik Porto Belóból. Több tucat kereskedô, akiket hadihajók védenek.  Mindig ugyanazon az útvonalon: Porto Belóból Havannába, majd ha elérte Kubát, északra hajózik az Óvilágba. Nyilvánvaló, hogy a flotta rakterei mérhetetlen kincsekkel vannak tele.",
};
/// Если новостей нет .
string NO_RUMOUR_TEXT[SIMPLE_RUMOUR_NUM] = {
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
"Azt mondják, hogy Európa megint fel fog robbanni. Újabb háború közeleg, és mint mindig, most is a köznép fog fizetni érte. Remélem, hogy nem fog ideérni, van elég saját problémánk.",
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
"Azt mondják, hogy Európa megint fel fog robbanni. Újabb háború közeleg, és mint mindig, most is a köznép fog fizetni érte. Remélem, hogy nem fog ideérni, van elég saját problémánk.",
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
"Azt mondják, hogy Európa megint fel fog robbanni. Újabb háború közeleg, és mint mindig, most is a köznép fog fizetni érte. Remélem, hogy nem fog ideérni, van elég saját problémánk.",
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
"Azt mondják, hogy Európa megint fel fog robbanni. Újabb háború közeleg, és mint mindig, most is a köznép fog fizetni érte. Remélem, hogy nem fog ideérni, van elég saját problémánk.",
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
"Azt mondják, hogy Európa megint fel fog robbanni. Újabb háború közeleg, és mint mindig, most is a köznép fog fizetni érte. Remélem, hogy nem fog ideérni, van elég saját problémánk.", //30
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
"Azt mondják, hogy Európa megint fel fog robbanni. Újabb háború közeleg, és mint mindig, most is a köznép fog fizetni érte. Remélem, hogy nem fog ideérni, van elég saját problémánk.",
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
"Azt mondják, hogy Európa megint fel fog robbanni. Újabb háború közeleg, és mint mindig, most is a köznép fog fizetni érte. Remélem, hogy nem fog ideérni, van elég saját problémánk.",
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
"Azt mondják, hogy Európa megint fel fog robbanni. Újabb háború közeleg, és mint mindig, most is a köznép fog fizetni érte. Remélem, hogy nem fog ideérni, van elég saját problémánk.",
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
"Azt mondják, hogy Európa megint fel fog robbanni. Újabb háború közeleg, és mint mindig, most is a köznép fog fizetni érte. Remélem, hogy nem fog ideérni, van elég saját problémánk.",
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
"Azt mondják, hogy Európa megint fel fog robbanni. Újabb háború közeleg, és mint mindig, most is a köznép fog fizetni érte. Remélem, hogy nem fog ideérni, van elég saját problémánk.", //60
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
"Azt mondják, hogy Európa megint fel fog robbanni. Újabb háború közeleg, és mint mindig, most is a köznép fog fizetni érte. Remélem, hogy nem fog ideérni, van elég saját problémánk.",
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
"Azt mondják, hogy Európa megint fel fog robbanni. Újabb háború közeleg, és mint mindig, most is a köznép fog fizetni érte. Remélem, hogy nem fog ideérni, van elég saját problémánk.",
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
"Azt mondják, hogy Európa megint fel fog robbanni. Újabb háború közeleg, és mint mindig, most is a köznép fog fizetni érte. Remélem, hogy nem fog ideérni, van elég saját problémánk.",
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
"Azt mondják, hogy Európa megint fel fog robbanni. Újabb háború közeleg, és mint mindig, most is a köznép fog fizetni érte. Remélem, hogy nem fog ideérni, van elég saját problémánk.",
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
"Azt mondják, hogy Európa megint fel fog robbanni. Újabb háború közeleg, és mint mindig, most is a köznép fog fizetni érte. Remélem, hogy nem fog ideérni, van elég saját problémánk.", //90
"Semmi különöset nem mondhatok. Az élet békésen és csendesen folyik. Meglepôen nyugodt, mondhatom.",
"Csend van errefelé. A hajók nem gyakran vetnek horgonyt a közelben, úgyhogy nincs semmi érdekes mondanivaló.",
"A hajójuk érkezése, errôl van szó!",
"Nem emlékszem semmi érdekesre. Még a kocsmai verekedések is ritkák itt.",
"Kétlem, hogy bármi különöset tudnék mondani, régen hallottam ilyen híreket.",
};

// Слухи капитанов
string CAPTAIN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Vigyázzatok a majdnem elsüllyedt hajókkal. Néhány kapitány talán felgyújtja a saját puskapor készleteit, csak hogy nektek és a szövetségeseiteknek egy utolsó csapást mérjenek a pokolból. Nem ez a leggyakoribb módja a búcsúzásnak, de azért legyetek óvatosak.",
"Ne becsülje alá az ágyúgolyókat, kapitány! Lehet, hogy közönségesnek és unalmasnak tûnnek, de a legnagyobb hatótávolsággal rendelkeznek, és szinte bármire képesek tisztességes sebzést okozni. Ráadásul olcsók. Ami mindig jó. Nem mindenki engedheti meg magának, hogy állandóan bombákat és lánclövéseket vásároljon.",
"Vigyázzatok a majdnem elsüllyedt hajókkal. Néhány kapitány talán felgyújtja a saját puskapor készleteit, csak hogy nektek és a szövetségeseiteknek egy utolsó csapást mérjenek a pokolból. Nem ez a leggyakoribb módja a búcsúzásnak, de azért legyetek óvatosak.",
"Ne becsülje alá az ágyúgolyókat, kapitány! Lehet, hogy közönségesnek és unalmasnak tûnnek, de a legnagyobb hatótávolsággal rendelkeznek, és szinte bármire képesek tisztességes sebzést okozni. Ráadásul olcsók. Ami mindig jó. Nem mindenki engedheti meg magának, hogy állandóan bombákat és lánclövéseket vásároljon.",
"Vigyázzatok a majdnem elsüllyedt hajókkal. Néhány kapitány talán felgyújtja a saját puskapor készleteit, csak hogy nektek és a szövetségeseiteknek egy utolsó csapást mérjenek a pokolból. Nem ez a leggyakoribb módja a búcsúzásnak, de azért legyetek óvatosak.",
"Ne becsülje alá az ágyúgolyókat, kapitány! Lehet, hogy közönségesnek és unalmasnak tûnnek, de a legnagyobb hatótávolsággal rendelkeznek, és szinte bármire képesek tisztességes sebzést okozni. Ráadásul olcsók. Ami mindig jó. Nem mindenki engedheti meg magának, hogy állandóan bombákat és lánclövéseket vásároljon.",
"Vigyázzatok a majdnem elsüllyedt hajókkal. Néhány kapitány talán felgyújtja a saját puskapor készleteit, csak hogy nektek és a szövetségeseiteknek egy utolsó csapást mérjenek a pokolból. Nem ez a leggyakoribb módja a búcsúzásnak, de azért legyetek óvatosak.",
"Ne becsülje alá az ágyúgolyókat, kapitány! Lehet, hogy közönségesnek és unalmasnak tûnnek, de a legnagyobb hatótávolsággal rendelkeznek, és szinte bármire képesek tisztességes sebzést okozni. Ráadásul olcsók. Ami mindig jó. Nem mindenki engedheti meg magának, hogy állandóan bombákat és lánclövéseket vásároljon.",
"Vigyázzatok a majdnem elsüllyedt hajókkal. Néhány kapitány talán felgyújtja a saját puskapor készleteit, csak hogy nektek és a szövetségeseiteknek egy utolsó csapást mérjenek a pokolból. Nem ez a leggyakoribb módja a búcsúzásnak, de azért legyetek óvatosak.",
"Ne becsülje alá az ágyúgolyókat, kapitány! Lehet, hogy közönségesnek és unalmasnak tûnnek, de a legnagyobb hatótávolsággal rendelkeznek, és szinte bármire képesek tisztességes sebzést okozni. Ráadásul olcsók. Ami mindig jó. Nem mindenki engedheti meg magának, hogy állandóan bombákat és lánclövéseket vásároljon.",
};

// Слухи мещан мужские
string CITIZEN_MAN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"A kereskedelemmel egy vagyont lehet keresni, mégis azt javaslom, hogy fogadj fel egy pénztárost, az üzlet itt, a kolóniákon trükkös. Egy jó pénztáros nélkül felfalnak téged és az érméidet. Szóval talán fontolóra kéne venned, hogy egy kormányzónak vagy valami hasonlónak dolgozz. Nem olyan kockázatos és nagyon tiszteletreméltó.",
"Menj el egy kocsmába, ha valami különlegeset keresel. Nincs mit mondanom neked.",
"A kereskedelemmel egy vagyont lehet keresni, mégis azt javaslom, hogy fogadj fel egy pénztárost, az üzlet itt, a kolóniákon trükkös. Egy jó pénztáros nélkül felfalnak téged és az érméidet. Szóval talán fontolóra kéne venned, hogy egy kormányzónak vagy valami hasonlónak dolgozz. Nem olyan kockázatos és nagyon tiszteletreméltó.",
"Menj el egy kocsmába, ha valami különlegeset keresel. Nincs mit mondanom neked.",
"A kereskedelemmel egy vagyont lehet keresni, mégis azt javaslom, hogy fogadj fel egy pénztárost, az üzlet itt, a kolóniákon trükkös. Egy jó pénztáros nélkül felfalnak téged és az érméidet. Szóval talán fontolóra kéne venned, hogy egy kormányzónak vagy valami hasonlónak dolgozz. Nem olyan kockázatos és nagyon tiszteletreméltó.",
"Menj el egy kocsmába, ha valami különlegeset keresel. Nincs mit mondanom neked.",
"A kereskedelemmel egy vagyont lehet keresni, mégis azt javaslom, hogy fogadj fel egy pénztárost, az üzlet itt, a kolóniákon trükkös. Egy jó pénztáros nélkül felfalnak téged és az érméidet. Szóval talán fontolóra kéne venned, hogy egy kormányzónak vagy valami hasonlónak dolgozz. Nem olyan kockázatos és nagyon tiszteletreméltó.",
"Menj el egy kocsmába, ha valami különlegeset keresel. Nincs mit mondanom neked.",
"A kereskedelemmel egy vagyont lehet keresni, mégis azt javaslom, hogy fogadj fel egy pénztárost, az üzlet itt, a kolóniákon trükkös. Egy jó pénztáros nélkül felfalnak téged és az érméidet. Szóval talán fontolóra kéne venned, hogy egy kormányzónak vagy valami hasonlónak dolgozz. Nem olyan kockázatos és nagyon tiszteletreméltó.",
"Menj el egy kocsmába, ha valami különlegeset keresel. Nincs mit mondanom neked.",
};

// Слухи мещан женские
string CITIZEN_WOMAN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Ha nem tudsz elég embert felvenni a kocsmákban, akkor keress az utcán. Néha a matrózok csak úgy kószálnak a városban, és keresik a megfelelô kapitányt.",
"Ez a hely barbár! Többnyire. A helyi emberek becsület nélküli vadállatok. Kérem, ne hagyják figyelmen kívül a segítségre szoruló nôket. Nagyon kevés védelmezônk van itt. Mutassanak némi méltóságot!",
"Ha nem tudsz elég embert felvenni a kocsmákban, akkor keress az utcán. Néha a matrózok csak úgy kószálnak a városban, és keresik a megfelelô kapitányt.",
"Ez a hely barbár! Többnyire. A helyi emberek becsület nélküli vadállatok. Kérem, ne hagyják figyelmen kívül a segítségre szoruló nôket. Nagyon kevés védelmezônk van itt. Mutassanak némi méltóságot!",
"Ha nem tudsz elég embert felvenni a kocsmákban, akkor keress az utcán. Néha a matrózok csak úgy kószálnak a városban, és keresik a megfelelô kapitányt.",
"Ez a hely barbár! Többnyire. A helyi emberek becsület nélküli vadállatok. Kérem, ne hagyják figyelmen kívül a segítségre szoruló nôket. Nagyon kevés védelmezônk van itt. Mutassanak némi méltóságot!",
"Ha nem tudsz elég embert felvenni a kocsmákban, akkor keress az utcán. Néha a matrózok csak úgy kószálnak a városban, és keresik a megfelelô kapitányt.",
"Ez a hely barbár! Többnyire. A helyi férfiak becsület nélküli vadállatok. Kérem, ne hagyják figyelmen kívül azokat a nôket, akik segítségre szorulnak. Olyan kevés védelmezônk van itt. Mutassanak némi méltóságot.",
"Ha nem tudsz elég embert felvenni a kocsmákban, akkor keress az utcán. Néha a matrózok csak úgy kószálnak a városban, és keresik a megfelelô kapitányt.",
"Ez a hely barbár! Többnyire. A helyi emberek becsület nélküli vadállatok. Kérem, ne hagyják figyelmen kívül a segítségre szoruló nôket. Nagyon kevés védelmezônk van itt. Mutassanak némi méltóságot!",
};

// Слухи дворян
string NOBLE_MAN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Uram, uralja a pengéjét. Megmenti az életét és megvédi a becsületét. De, hogy teljesen ôszinte legyek, a helyi csavargók nem pengét, hanem fejszét érdemelnek.",
"Mindig legyen elég puskapor és töltény a rendelkezésedre. Nem akarsz kifogyni a lôszerbôl a harc közepén. Jó lenne egy plusz fegyvert is tartani. Azok a dolgok gyakran felrobbannak...",
"Uram, uralja a pengéjét. Megmenti az életét és megvédi a becsületét. De, hogy teljesen ôszinte legyek, a helyi csavargók nem pengét, hanem fejszét érdemelnek.",
"Mindig legyen elég puskapor és töltény a rendelkezésedre. Nem akarsz kifogyni a lôszerbôl a harc közepén. Jó lenne egy plusz fegyvert is tartani. Azok a dolgok gyakran felrobbannak...",
"Uram, uralja a pengéjét. Megmenti az életét és megvédi a becsületét. De, hogy teljesen ôszinte legyek, a helyi csavargók nem pengét, hanem fejszét érdemelnek.",
"Mindig legyen elég puskapor és töltény a rendelkezésedre. Nem akarsz kifogyni a lôszerbôl a harc közepén. Jó lenne egy plusz fegyvert is tartani. Azok a dolgok gyakran felrobbannak...",
"Uram, uralja a pengéjét. Megmenti az életét és megvédi a becsületét. De, hogy teljesen ôszinte legyek, a helyi csavargók nem pengét, hanem fejszét érdemelnek.",
"Mindig legyen elég puskapor és töltény a rendelkezésedre. Nem akarsz kifogyni a lôszerbôl a harc közepén. Jó lenne egy plusz fegyvert is tartani. Azok a dolgok gyakran felrobbannak...",
"Uram, uralja a pengéjét. Megmenti az életét és megvédi a becsületét. De, hogy teljesen ôszinte legyek, a helyi csavargók nem pengét, hanem fejszét érdemelnek.",
"Mindig legyen elég puskapor és töltény a rendelkezésedre. Nem akarsz kifogyni a lôszerbôl a harc közepén. Jó lenne egy plusz fegyvert is tartani. Azok a dolgok gyakran felrobbannak...",
};

// Слухи дворянок
string NOBLE_WOMAN_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Úgy nézel ki, mint egy becsületes ember. Egy nemes ember. Ha más típus lennél, elküldenélek egy kocsmába, hogy ott kérdezôsködj az emberektôl.",
"Tudtad, kapitány, hogy mindenféle mágikus tárgyak vannak errefelé? Lehet, hogy az egyház nem hagyja jóvá, de mindenki használ talizmánokat és amuletteket.",
"Úgy nézel ki, mint egy becsületes ember. Egy nemes ember. Ha más típus lennél, elküldenélek egy kocsmába, hogy ott kérdezôsködj az emberektôl.",
"Tudtad, kapitány, hogy mindenféle mágikus tárgyak vannak errefelé? Lehet, hogy az egyház nem hagyja jóvá, de mindenki használ talizmánokat és amuletteket.",
"Úgy nézel ki, mint egy becsületes ember. Egy nemes ember. Ha más típus lennél, elküldenélek egy kocsmába, hogy ott kérdezôsködj az emberektôl.",
"Tudtad, kapitány, hogy mindenféle mágikus tárgyak vannak errefelé? Lehet, hogy az egyház nem hagyja jóvá, de mindenki használ talizmánokat és amuletteket.",
"Úgy nézel ki, mint egy becsületes ember. Egy nemes ember. Ha más típus lennél, elküldenélek egy kocsmába, hogy ott kérdezôsködj az emberektôl.",
"Tudtad, kapitány, hogy mindenféle mágikus tárgyak vannak errefelé? Lehet, hogy az egyház nem hagyja jóvá, de mindenki használ talizmánokat és amuletteket.",
"Úgy nézel ki, mint egy becsületes ember. Egy nemes ember. Ha más típus lennél, elküldenélek egy kocsmába, hogy ott kérdezôsködj az emberektôl.",
"Tudtad, kapitány, hogy mindenféle mágikus tárgyak vannak errefelé? Lehet, hogy az egyház nem hagyja jóvá, de mindenki használ talizmánokat és amuletteket.",
};

// Слухи матросов
string SAILOR_RUMOUR_TEXT[CITIZEN_RUMOUR_NUM] = {
"Nehéz manapság rendes kapitányt találni. A legtöbbjük azt akarja, hogy a katonái vagy rabszolgái legyünk. Vagy mindkettô. Csesszék meg. Remélem, te más vagy.",
"Semmi érdekes. Érdekes lesz, ha elfogynak az ellátmányaink.",
"Nehéz manapság rendes kapitányt találni. A legtöbbjük azt akarja, hogy a katonái vagy rabszolgái legyünk. Vagy mindkettô. Csesszék meg. Remélem, te más vagy.",
"Semmi érdekes. Érdekes lesz, ha elfogynak az ellátmányaink.",
"Nehéz manapság rendes kapitányt találni. A legtöbbjük azt akarja, hogy a katonái vagy rabszolgái legyünk. Vagy mindkettô. Csesszék meg. Remélem, te más vagy.",
"Semmi érdekes. Érdekes lesz, ha elfogynak az ellátmányaink.",
"Nehéz manapság rendes kapitányt találni. A legtöbbjük azt akarja, hogy a katonái vagy rabszolgái legyünk. Vagy mindkettô. Csesszék meg. Remélem, te más vagy.",
"Semmi érdekes. Érdekes lesz, ha elfogynak az ellátmányaink.",
"Nehéz manapság rendes kapitányt találni. A legtöbbjük azt akarja, hogy a katonái vagy rabszolgái legyünk. Vagy mindkettô. Csesszék meg. Remélem, te más vagy.",
"Semmi érdekes. Érdekes lesz, ha elfogynak az ellátmányaink.",
};

// Если новостей нет в LSC
string NO_RUMOUR_LSC_TEXT[5] = {
"Elég unalmas itt. Milyen hírek érdekelnek?",
"Pletykák? Nincs mit mondanom, jól megleszünk, amíg a Rivados és a Narwals nem kezdenek újra harcolni.",
"Semmi érdekes... Érdekes lesz, amikor az élelmiszerkészleteink elfogynak.",
"Ugyanaz, mint mindig. Unalmas. Talán a kalózok szétrúgják a klánok' arát. Az biztosan jó hangulatot csinálna.",
"Semmi hír, semmi pletyka. Amíg a klánok el nem kezdik gyilkolni egymást, persze.",
};
