

native int rand(int m);
native float frnd();
native int CreateEntity(ref rObj, string sName);
native void DeleteClass(ref rObj);
native void SetEventHandler(string sEventName, string sHandlerName, int iFlag);
native void ExitProgram();
native ref GetEventData();
native uint SendMessage(ref rObj, string sFormat, ...);
native int LoadSegment(string s);
native void UnloadSegment(string s);
native void Trace(string s);
native void LayerSetRealize(int iIdx);
native void LayerSetExecute(int iIdx);
native void LayerAddObject(int iIdx, ref rObj, int iPriority);
native void LayerDelObject(int iIdx, ref rObj);
native void LayerFreeze(int iIdx, bool bFreeze);
native ref abs(float arg);
native float sqrt(float arg);
native float sqr(float arg);
native float sin(float arg);
native float cos(float arg);
native float tan(float arg);
native float atan(float arg);
native float atan2(float lhs, float rhs);
native float asin(float arg);
native float acos(float arg);
native void DeleteAttribute(aref ar, string s);
native int SegmentIsLoaded(string sSegName);
native int GetAttributesNum(aref ar);
native aref GetAttributeN(aref ar, int n);
native string GetAttributeName(aref ar);
native void DelEventHandler(string sEventName, string sHandlerName);
native void EntityUpdate(bool b);
native bool IsEntity(ref rObj);
native void DumpAttributes(ref rObj);
native int argb(int a, int r, int g, int b);
native void DeleteEntities();
native void ClearEvents();
native void SaveEngineState(string s);
native void LoadEngineState(string s);
native void Event(string sName, ...);
native void PostEvent(string sName, int iDelay, ...);
native string fts(float f);
native void ClearPostEvents();
native void SetArraySize(ref r, int n);
native string GetAttributeValue(aref ar);
native string Vartype(ref r);
native void Breakpoint();
native float Pow(float lhs, float rhs);
native void CopyAttributes(ref arDst, ref arSrc);
native string strcut(string s, int l, int r);
native int findSubStr();
native void ClearRef(ref r);
native int strlen(string s);
native int GetDeltaTime();
native void EventsBreak();
native int shl(int lhs, int rhs);
native int shr(int lhs, int rhs);
native int and(int lhs, int rhs);
native int or(int lhs, int rhs);
native void DeleteEntitiesByType(string s);
native int CreateControl(string s);
native void DeleteControl(string s);
native void MapControl(int arg1, int arg2, int arg3);
native void SetControlFlags(int iCntrlCode, int iControlState);
native void ClearEntityAP(ref r);
native int GetArraySize(ref r);
native string GetTargetPlatform();
native int GetEntity(ref r, string s);
native int FindEntity(ref r, string s);
native int FindEntityNext(ref r);
native string GetSymbol(string s, int n);
native int IsDigit(string s, int n);
native void SetControlTreshold(int i, float f);
native void LockControl(string s, int i);
native int TestRef(ref r);
native void SetTimeScale(float fScale);
native int CheckFunction(string sFuncName);
native int GetEngineVersion();
native void UpdateControlGroup(int iIdx);
native void CollectCallStack();
native int hash(string s);
native int hrand(int iMax, ...);
native void __CreateRecoveryFile();
native int GetRDeltaTime();
native void SetEventHandlerForObject(aref arObj, string sEventName, string sHandlerName, int iFlag);
native void DelEventHandlerForObject(aref arObj, string sEventName, string sHandlerName);
native void EventForObject(aref arObj, string sName, ...);
native void PostEventForObject(aref arObj, string sName, int iDelay, ...);
native void SetEventFormat(string sName, string sFormat);
native void SetEventStaticHandler(string sEventName, string sHandlerName, int iFlag);
native void SetEventStaticHandlerForObject(aref arObj, string sEventName, string sHandlerName, int iFlag);
native void SmartSort(ref rObj, string sColName, string sDataType, bool bAsc, int iOffset, string sPrefix);
native void ClearPostEventsForEvent(string sEventName);
native int GetArgCount();
native ref GetArg(int iNum);
native void assert(bool bCond, ...);
native string GetLastCommit();
native string Sprintf(string sFormat, ...);
native void ArrayShuffle(ref rArr);
native void ArraySort(ref rArr, ...);
native string GetPrevFuncName();
native int CreateIndex(ref rArr, ref rKeysArr, ...);
native void RebuildIndex(int iIndexID);
native void DeleteIndex(int iIndexID);
native void FindByIndex(int iIndexID, ref rResult, ...);
native string DLGO(string sInput, ...);
native string DLG_Convert(string sKey, string sFilename, ...);
native string DLG_ConvertE(string sKey, string sFilename, ...);
native void DLG_ReplaceAllMatches(ref rInput, string sKey, string sReplace, ...);
native string GetTypeNameByTypeID(int iTypeID);
native void RunScriptTests();
native void GetScriptProfile();
native void ResetScriptProfile();
native void SetClasstable(ref rObject, ref rClasstable);
native bool attrrename(ref rAttr, string sName);