#define BRDLT_SHIP	0
#define BRDLT_FORT	1

#define BRDLT_MAXCREW 60

#define LOCINITBRD_DEFAULTLOCATION "BOARDING_5_WAR"
#define LOCINITBRD_DEFAULTLOCATION_FORT "Any_fort_1"

#define MAX_GROUP_SIZE   24