string DLG_TEXT[229] = {      
"Helló. Hadd adjak egy szerény tanácsot.",
"Örömmel meghallgatom.",
"Nincs szükségem a tanácsodra.",
"Üdvözletem. Sietsz?",
"Igen, üzleti ügyben.",
"Nem tartozik magára.",
"Jó napot, uram. Hogy van?",
"Semmi.",
"Nincs idôm itt beszélgetni.",
"Jó napot! Jó napot! Még nem láttam itt magát.",
"Igen, átutazóban vagyok.",
"Nincs idôm itt beszélgetni.",
"Üdvözlöm. Örülök, hogy a környékünkön látom.",
"Üdvözlöm!",
"Sajnálom, most nem tudok beszélni önnel.",
"Jó napot! Jó napot! Akarsz hallani egy jó tanácsot?",
"Üdvözlöm. Gyerünk, mondd el.",
"Nem akarom vesztegetni az idômet.",
"Szia. Van néhány dolog, ami érdekelhet.",
"Alkudozzunk.",
"Nincs idôm itt beszélgetni.",
"Jó napot! Jó napot! Fáradtnak tûnik. Csak 200 érméért meggyógyítom a sebeidet és enyhítem a fáradtságodat.",
"Add ide az italodat.",
"Nem hiszek a csodaszerekben.",
"Jó napot, uram. Kényszerhelyzetben vagyok, tudsz segíteni?",
"Hmm, miért vagyok...",
"Ezek a te problémáid, oldd meg ôket magad.",
"Nem akarsz segíteni szegény szenvedônek, nem könnyíted meg a sorsát néhány érmével?",
"Persze, az egyház arra tanít minket, hogy figyeljünk, és segítsünk a másikon.",
"Menj tovább, szegény ember, és ne merj még egyszer közeledni hozzám.",
"Ne hagyj itt egy koldust a bajban, adnál egy érmét, hogy ne haljak éhen.",
"Mirôl beszélsz, tartsd meg a 200 érmét.",
"Menj tovább, szegény ember, és ne merj még egyszer közeledni hozzám.",
"Jó napot! Látom, hogy fegyvered van, biztosan gyakran veszel részt verekedésekben?",
"Igen, persze.",
"Ez az én dolgom. Viszontlátásra.",
"Jó napot. Nem gyakran látni ilyen fontos személyt a vadonban. Maga biztos a kapitány?",
"Igen, miben segíthetek?",
"Tudja, sietek. Viszontlátásra.",
"Jó napot, uram. Csak úgy itt sétálgatsz, és nem csinálsz semmit?",
"Valójában igen, tudok beszélni magával.",
"Nem, nem érek rá.",
"Figyelj, ne jelenj meg éjszaka a dzsungelben. A banditák gyakran járnak oda, és figyelmeztetés nélkül támadnak.",
"Köszönöm a tanácsot.",
"Ha bajban vagy a törvénnyel, akkor jobb, ha nem futsz bele egy ôrjáratba. Rengeteg katona van itt. Jobb, ha elhagyod a szigetet.",
"Érdekes.",
"Engem nem érdekelnek az ilyen tanácsok. Viszontlátásra.",
"De készüljön fel a hideg fogadtatásra, ha legközelebb ide hajózik.",
"Rendben, figyelembe veszem, viszlát.",
"Tudok egy biztos módszert az egészség helyreállítására, ha valami baj van veled. Vehetsz egy üveggel egy árustól a városban.",
"Igen, és azon kívül?",
"Nincs idôm beszélgetni.",
"Nos, az is, ha a kocsmában pihensz, az növeli az életerôdet.",
"Köszönöm.",
"Tudod, ha a legfrissebb hírekre vagy bármilyen információra van szükségem, mindig a kocsmároshoz megyek. Ô szinte minden kérdésedre tud válaszolni.",
"Remek tanács, használni fogom.",
"Látom, hogy maga katona. És részt kell venned a harcokban. Ne felejts el több tisztet magaddal vinni. Néha lehetetlen túlélni erôsítés nélkül.",
"Igen, persze.",
"Látom az álláspontodból, hogy te vagy a kapitány, nem kevesebb. Ha hajóra van szükséged, vedd meg a hajógyárunkban. Ha hirtelen nem éppen az a hajó van, amit meg akartál venni, gyere vissza néhány nap múlva, talán addigra már eladó lesz.",
"Jó tanács, köszönöm.",
"Néha olyan emberek jelennek meg ezeken a helyeken, akik már sokat láttak ebben a világban. Tôlük kérhetsz segítséget, és ôk egy vagy több területen fejleszteni tudják a képességeidet. Én biztosan tudom, hogy a tudásuk szinte felbecsülhetetlen.",
"Jó tanács, köszönöm.",
"Ha adsz nekem 200 érmét, mindenkinek elmondom, milyen csodálatos ember vagy. Nem számít, hogy szegény vagyok, sok barátom van, itt mindig szívesen látnak.",
"Pénzzel dobálózni, csak hogy valami bolond meséljen rólam? Hát, nem.",
"Igen? Nos, 200 érme nem akkora összeg, hogy ne adnád oda valakinek, akinek nagy szüksége van rá.",
"Köszönöm, amit tettél. Ezt én is megköszönöm, ahogy csak tudom. Igya meg ezt a tinktúrát, visszaadja az életerejét.",
"Neked is köszönöm.",
"Köszönöm, de nincs semmim, amit adhatnék, amivel kifejezhetném hálámat, fogadd el ezt a kis apróságot, talán hasznodra válhat.",
"Örömmel elfogadom az ajándékodat.",
"Köszönöm, nagyon kedves vagy.",
"Nem, köszönöm, viszlát.",
"Kapitány, vigyen a hajójára, régóta álmodom hosszú tengeri utakról és ádáz csatákról.",
"Természetesen ön lesz a tisztem.",
"Nem, nincs szükségem újoncokra.",
"Fizess nekem, és megmutatok néhány trükköt, amivel bárkit legyôzhetsz közelharcban. Vagy szeretnél megtanulni néhány védekezô mozdulatot?",
"Nincs szükségem a tanácsaidra, már mindent tudok.",
"Mutasd meg a védekezési technikákat.",
"Nincs szükségem a tanácsaidra, már mindent tudok.",
"Mutasd meg, hogyan kell támadni.",
"Köszönöm, nincs szükségem semmire.",
"Én is tengerész voltam valaha, egy híres navigátor. Sokat tudok mondani arról, hogyan kell irányítani a legénységet egy hajón.",
"Nincs szükségem a tanácsaidra, már mindent tudok.",
"Igen, szeretnék többet tudni errôl.",
"Köszönöm, nincs szükségem semmire.",
"Én is tengerész vagyok, navigátor. Egy kis díjért elárulom a titkaimat, amelyek segítségével jobban irányíthatod a hajót.",
"Nincs szükségem a tanácsaidra, már mindent tudok.",
"Igen, szeretném megtudni a manôverezési titkait.",
"Köszönöm, nincs szükségem semmire.",
"Tüzér voltam egy brit hadihajón. Szívesen elmondom, hogyan kell helyesen kiszámítani az ágyúgolyó röppályáját, és minden alkalommal eltalálni a célt.",
"Nincs szükségem a tanácsaidra, már mindent tudok.",
"Mondja el, annyit fizetek, amennyit kér.",
"Köszönöm, nincs szükségem semmire.",
"Tüzér voltam egy brit hadihajón. Meg tudom mondani, hogyan kell gyorsan újratölteni az ágyúkat.",
"Nincs szükségem a tanácsaidra, már mindent tudok.",
"Mondja el, annyit fizetek, amennyit kér.",
"Köszönöm, nincs szükségem semmire.",
"Tiszt voltam egy brit hadihajón. Sok történetet tudok mesélni a partraszállás mûvészetérôl.",
"Nincs szükségem a tanácsaidra, már mindent tudok.",
"Mondja el, annyit fizetek, amennyit kér.",
"Köszönöm, nincs szükségem semmire.",
"Egy hajógyárban dolgozom, és nagyon értek a hajók építéséhez és javításához. Ha fizetsz nekem, kiképzem a legénységedet, hogy hogyan javítson meg gyorsan egy hajót.",
"Nincs szükségem a tanácsaidra, már mindent tudok.",
"Mondja el, annyit fizetek, amennyit kér.",
"Köszönöm, nincs szükségem semmire.",
"Kereskedô vagyok, megtaníthatom neked a kereskedelmi technikákat, amelyekkel növelheted az üzleti vállalkozásodból származó nyereséget.",
"Nincs szükségem a tanácsaidra, már mindent tudok.",
"Mondja el, annyit fizetek, amennyit kér.",
"Köszönöm, nincs szükségem semmire.",
"Nos, ha fizetsz nekem,",
"?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Nos, akkor fizetni fogsz nekem,",
"a titkos közelharci technikákért?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Nos, akkor fizetni fogsz nekem,",
"?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Nos, ha fizetsz nekem,",
"titkos védelmi technikákért?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Nos, ha fizetsz nekem,",
"?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Nos, ha fizetsz nekem,",
"az emberek vezetésének leckéiért?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Nos, ha fizetsz nekem,",
"?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Nos, ha fizetsz nekem,",
"tanácsokért a hajó irányításával kapcsolatban?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Nos, ha fizetsz nekem,",
"?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Nos, ha fizetsz nekem,",
"az ágyúk elsütésével kapcsolatos tanácsokért?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Nos, ha fizetsz nekem,",
"?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Nos, ha fizetsz nekem,",
"az ágyúk újratöltésével kapcsolatos tanácsokért?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Nos, ha fizetsz nekem,",
"?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Nos, ha fizetsz nekem,",
"az abortuszra vonatkozó tanácsokért?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Nos, mennyit fog fizetni nekem,",
"?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Nos, ha fizetsz nekem,",
"a hajó javításával kapcsolatos tanácsokért?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Nos, ha fizetsz nekem,",
"?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Nos, ha fizetsz nekem,",
"a kereskedelemben való segítségért?",
"Úgy tûnik, nincs elég pénzem.",
"Igen, megpróbálom, mondd csak.",
"Nem, ez túl sok.",
"Köszönöm a segítséget, túlságosan kedvesek vagytok.",
"Nem szükséges, örülök, hogy segíthettem.",
"Nos, szeretnél még több elixírt venni?",
"Igen, talán többet is.",
"Nem, sajnálom.",
"Nos, akarsz alkudozni?",
"Igen, szeretnék venni valamit tôled.",
"Nem, sajnálom.",
"Mit akarsz? Azt hiszem, már mindent megbeszéltünk.",
"Nem érdekes.",
"Milyen parancsot, kapitány?",
"Nincs",
"Tanácsot akarsz?",
"Igen, érdekel, mit akar mondani.",
"Nem, sajnálom.",
"Figyelj, élj tisztességes életet, és sok ember boldog lesz veled.",
"Köszönöm a tanácsot.",
"Nem tanácsolom, hogy ide jöjjön, ha bajban van a törvénnyel. Sok katona van itt. Jobb, ha elhajózol a szigetrôl.",
"Érdekes.",
"Engem nem érdekelnek az ilyen tanácsok. Viszontlátásra.",
"Tudok egy biztos módszert az egészség helyreállítására, ha valami baj van veled. Vásárolhatsz egy üveggel egy árustól a városban.",
"Igen, és azon kívül?",
"Nincs idôm beszélgetni.",
"Tudod, ha friss hírekre vagy bármilyen információra van szükségem, mindig a fogadóshoz fordulok. Ô szinte minden kérdésedre tud válaszolni.",
"Remek tanács, használni fogom.",
"Látom, hogy ön katona. És gyakran kell részt venned harcokban. Ne feledje, hogy több tisztet is vigyen magával. Néha lehetetlen túlélni erôsítés nélkül.",
"Igen, persze.",
"Látom az álláspontodból, hogy te vagy a kapitány, nem kevesebb. Ha hajóra van szükséged, vedd meg a hajógyárunkban. Ha hirtelen nem éppen az a hajó van, amit meg akartál venni, gyere vissza néhány nap múlva, talán addigra már eladó lesz.",
"Jó tanács, köszönöm.",
"Néha olyan emberek jelennek meg ezeken a helyeken, akik sokat láttak már ebben a világban. Segítséget kérhetsz tôlük, és ôk képesek lesznek növelni a tudásod szintjét egy vagy több területen. Biztosan tudom, hogy a tudásuk szinte felbecsülhetetlen.",
"Jó tanács, köszönöm.",
};